return {

	{ 'ful1e5/onedark.nvim', priority=1000, config = function() require('onedark').setup() end },
	{ 'xiyaowong/nvim-transparent',
		config = function()
			require("transparent").setup({
				groups = { -- table: default groups
					'Normal', 'NormalNC', 'Comment', 'Constant', 'Special', 'Identifier',
					'Statement', 'PreProc', 'Type', 'Underlined', 'Todo', 'String', 'Function',
					'Conditional', 'Repeat', 'Operator', 'Structure', 'LineNr', 'NonText',
					'SignColumn', 'CursorLineNr', 'EndOfBuffer',
				  },
				extra_groups = {
					"NvimTreeNormal",
					"NvimTreeNormalNC",
					"NvimTreeStatusLine",
					"NvimTreeStatusLineNC",
					"Normal",
					"NormalNC",
					"Comment",
					"Constant",
					"Special",
					"Identifier",
					"Statement",
					"PreProc",
					"Type",
					"Underlined",
					"Todo",
					"String",
					"Function",
					"Conditional",
					"Repeat",
					"Operator",
					"Structure",
					"LineNr",
					"NonText",
					"SignColumn",
					"CursorLineNr",
					"FloatBorder",
					"TelescopeNormal",
					"TelescopeBorder",
					"WhichKeyFloat",
					-- "StatusLine",
					-- "StatusLineNC",
					"WildMenu",
					"Folded",
					"FoldColumn",
					"QuickFixLine",
					"NormalFloat",

					"BufferCurrent",
					"BufferCurrentMod",
					"BufferCurrentSign",
					"BufferVisible",
					"BufferCurrentIndex",
					"BufferVisibleIndex",
					"BufferVisibleSign",
					"BufferCurrentTarget",
					"BufferVisibleTarget",
					"BufferInactive",
					"BufferInactiveMod",
					"BufferInactiveIndex",
					"BufferInactiveSign",
					"BufferInactiveTarget",
					"NormalSB",
					"SignColumnSB"
				},
				exclude_groups = {},
			})
		end,
	}
}
